source 'https://rubygems.org'
gem 'rspec', :require => 'spec'
gem 'rake', :require => 'rake'
gem 'nokogiri', :require => 'nokogiri'
#gem '', :require => 'fileutils'
#gem '', :require => "yaml"
#gem '', :require => 'rss/1.0'
#gem '', :require => 'rss/2.0'
#gem '', :require => 'open-uri'
#gem '', :require => 'net/http'
