# vim: ft=yaml:sts=2:expandtab

####################################################
# Place all environment configfuration values here #
####################################################

deploymentName: nil
typo3:
    # show all versions with rake t3_versions
    t3version: 4.7.10

    dbname: nil
    dbuser: nil
    dbpass: nil
    dbhost: nil

    # Choose one of the sourceforge mirrors:
    # North America:        iweb, superb-sea2, voxel, cdnetworks-us-1, cdnetworks-us-2
    # South America:        ufpr,
    # Europe:               dfn, freefr ,garr, mesh, kent, heanet, surfnet, ovh, sunet, switch, citylan, ignum, netcologne,
    # Australia:            waix, transact, internode, aarnet,
    # Asia:                 jaist, ncu, nchc, cdnetworks-kr-1, cdnetworks-kr-2,
    # Africa:               tenet    
    sfmirror: netcologne

    sysExtList: 
       - cms
       - version
       - em
       - tsconfig_help
       - context_help
       - extra_page_cm_options
       - impexp
       - sys_note
       - tstemplate
       - tstemplate_ceditor
       - tstemplate_info
       - tstemplate_objbrowser
       - tstemplate_analyzer
       - func_wizards
       - wizard_crpages
       - wizard_sortpages
       - lowlevel
       - install
       - belog
       - beuser
       - aboutmodules
       - setup
       - taskcenter
       - info_pagetsconfig
       - viewpage
       - rtehtmlarea
       - css_styled_content
       - t3skin
       - t3editor
       - reports 
       - extbase

extBundles:
   pas3core:
      type: git # git/svn/?
      uri: https://github.com/PAS3/typo3-pas3-core.git 
      branch: master                                             # not implemented yet
   lwinfra:
      type: svn
      uri: https://pim@svn.lingewoud.net/svn/typo3ext/lwinfra

extSingles:
   lsd_deployt3iu:   
      type: git
      uri: https://github.com/Lingewoud/lsd_deployt3iu.git
   templavoila:
      type: ter # git/svn/ter/t3x/zip/?                           # ter/git only implemented
      uri: templavoila
      version: 1.8.0
   cc_textfunc:
      type: git
      uri: https://github.com/mipmip/cc_textfunc.git
   static_info_tables:
      type: ter 
      uri: static_info_tables
      version: 2.3.1
   dam:
      type: ter
      uri: dam
      version: 1.3.1

TYPO3_CONF_VARS_SYS:
   sitename: My TYPO3 Site

beuser:
   admin:
      username: admin
      password: password
      admin: 1
      email: admin@mysite.com

TYPO3_CONF_VARS_EXT:
   extConf:
      p3core_refx:
         refxAddress: 172.16.145.1:3000
         pas3RemoteDummyRoot: /Volumes/pas3/dummy
      dam:
         file_filelist: 0

TYPO3_CONF_VARS_GFX:
   TTFdpi: 96
   im_noFramePrepended: im_noFramePrepended
   gdlib_png: 1
   png_truecolor: 1
   jpg_quality: 90
   thumbnails_png: 1
   gdlib_2: 1

appendPHPToFile:
    tools:
        file: typo3/mod/tools/conf.php
        appendPHPCode: |
            $MCONF['access']='user,group';
#    cooluri:
#        file: typo3conf/ext/cooluri/mod1/conf.php
#        appendPHPCode: |
#            $MCONF['access']='user,group';


